# Companion to docs/en/api.en.md section 2, Python half. Every region between [doc:id] and [doc:/id]
# is the code the fence tagged `doc:id` shows.
#
# The adapters this imports are generated by test/test_doc_adapter.py before it imports this
# module -- my_pkg/Cloud from docs/examples/Cloud.msg, sensor_msgs/Image from the installed
# message. Importing is what checks the generated module surface; the publish region is also
# called, because build() and commit() only exist against a real Publisher and so are the two
# names the generator's own tests cannot reach.

import flux
import flux.ros

from my_pkg_flux.cloud import Cloud
from sensor_msgs_flux.image import Image
from sensor_msgs_flux.image_ros import frame_to_msg, msg_to_frame


def _sink(*_args):
    pass


def doc_publish(node, n, xs):
    # [doc:adapter_py_pub]
    pub = flux.ros.Publisher(node, "cloud", fingerprint=Cloud.FINGERPRINT__)

    b = Cloud.build__(pub)
    if b:
        b.alloc__x(n)[:] = xs
        b.width = n
        b.label = "front"
        b.commit__()
    # [doc:/adapter_py_pub]
    return pub, b


def doc_subscribe(node):
    # [doc:adapter_py_sub]
    sub = flux.ros.Subscription(node, "cloud", fingerprint=Cloud.FINGERPRINT__)

    f = sub.take()
    if f is not None:
        c = Cloud.View(f)
        print(c.x, c.width, c.label)
    # [doc:/adapter_py_sub]
    return sub


def doc_bridge(pub, img, f):
    # [doc:adapter_py_bridge]
    b = Image.build__(pub)
    msg_to_frame(img, b)
    b.commit__()

    back = frame_to_msg(Image.View(f))
    # [doc:/adapter_py_bridge]
    _sink(back)
