# flux_generate_adapters(<.msg files, relative to the current source dir>...)
#
# Generates, per message, a C++ header and a Python module that read and write the flat frame
# layout flux_gen computes, and installs both:
#
#   include/<pkg>/flux/<snake>.hpp   ->  <pkg>::flux_msg::<Msg>
#   <pkg>_flux/<snake>.py           ->  <pkg>_flux.<snake>.<Msg>
#
# Opt-in per message, like the rest of flux -- listing a .msg here does not change how the
# package's normal ROS interfaces are built. The headers are emitted as plain text and compiled
# by whoever includes them, so a message package needs no build dependency on flux_cpp; consumers
# include the header and link flux_cpp themselves.
#
# A schema's layout and fingerprint depend on every nested type it reads, so the generator writes
# a depfile naming them. Editing a nested .msg regenerates its carriers; without that a stale
# adapter is not a build error but a fingerprint that no longer matches its peer at runtime.
#
# A macro, not a function, for the same reason rosidl_generate_interfaces is one:
# ament_export_include_directories() appends to a variable in its caller's domain, and a function
# would swallow it -- the headers would install but no consumer could find them. Locals are
# _flux_-prefixed since a macro shares the caller's domain.

macro(flux_generate_adapters)
  # ARGN is not a real variable inside a macro -- it only exists as ${ARGN} -- so capture it.
  set(_flux_msgs "${ARGN}")
  if(NOT _flux_msgs)
    message(FATAL_ERROR "flux_generate_adapters() called without any .msg files")
  endif()

  find_package(Python3 REQUIRED COMPONENTS Interpreter)

  # The generator itself is an input: an emitter edit or a FINGERPRINT_SCHEMA_VERSION bump must
  # regenerate every consumer, or a stale adapter is not a build error but a fingerprint that no
  # longer matches its peer at runtime.
  file(GLOB _flux_gen_sources CONFIGURE_DEPENDS "${FLUX_GEN_PYTHON_DIR}/flux_gen/*.py")

  set(_flux_root "${CMAKE_CURRENT_BINARY_DIR}/flux_adapters")
  set(_flux_cpp_root "${_flux_root}/include")
  set(_flux_py_root "${_flux_root}/python")
  set(_flux_outputs "")
  set(_flux_modules "")

  foreach(_flux_msg IN LISTS _flux_msgs)
    get_filename_component(_flux_name "${_flux_msg}" NAME_WE)
    # CamelCase -> snake_case, matching the generator's own file naming.
    string(REGEX REPLACE "(.)([A-Z][a-z]+)" "\\1_\\2" _flux_snake "${_flux_name}")
    string(REGEX REPLACE "([a-z0-9])([A-Z])" "\\1_\\2" _flux_snake "${_flux_snake}")
    string(TOLOWER "${_flux_snake}" _flux_snake)

    set(_flux_hpp "${_flux_cpp_root}/${PROJECT_NAME}/flux/${_flux_snake}.hpp")
    set(_flux_py "${_flux_py_root}/${PROJECT_NAME}_flux/${_flux_snake}.py")
    # The ROS bridge is a second pair, kept apart so the base adapter includes no rosidl header.
    set(_flux_hpp_ros "${_flux_cpp_root}/${PROJECT_NAME}/flux/${_flux_snake}_ros.hpp")
    set(_flux_py_ros "${_flux_py_root}/${PROJECT_NAME}_flux/${_flux_snake}_ros.py")
    set(_flux_dep "${_flux_root}/${_flux_snake}.d")

    add_custom_command(
      OUTPUT "${_flux_hpp}" "${_flux_py}" "${_flux_hpp_ros}" "${_flux_py_ros}"
      COMMAND ${CMAKE_COMMAND} -E env
              "PYTHONPATH=${FLUX_GEN_PYTHON_DIR}:$ENV{PYTHONPATH}"
              ${Python3_EXECUTABLE} -m flux_gen
              --pkg ${PROJECT_NAME}
              --msg "${CMAKE_CURRENT_SOURCE_DIR}/${_flux_msg}"
              --out-cpp "${_flux_cpp_root}"
              --out-py "${_flux_py_root}"
              --depfile "${_flux_dep}"
      DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/${_flux_msg}" ${_flux_gen_sources}
      DEPFILE "${_flux_dep}"
      COMMENT "flux_gen: ${PROJECT_NAME}/${_flux_name}"
      VERBATIM)

    list(APPEND _flux_outputs
      "${_flux_hpp}" "${_flux_py}" "${_flux_hpp_ros}" "${_flux_py_ros}")
    list(APPEND _flux_modules "${_flux_snake}")
  endforeach()

  set(_flux_init "# generated by flux_generate_adapters -- do not edit.\n")
  foreach(_flux_mod ${_flux_modules})
    string(APPEND _flux_init "from .${_flux_mod} import *  # noqa: F401,F403\n")
  endforeach()
  file(GENERATE
    OUTPUT "${_flux_py_root}/${PROJECT_NAME}_flux/__init__.py"
    CONTENT "${_flux_init}")

  add_custom_target(${PROJECT_NAME}_flux_adapters ALL DEPENDS ${_flux_outputs})

  # rosidl puts a package's headers at include/<pkg>/<pkg>/..., so the exported include dir is
  # include/<pkg> and an adapter resolves as <pkg>/flux/<name>.hpp. Matching that layout keeps
  # one export correct whether or not the package also generates ROS interfaces.
  install(DIRECTORY "${_flux_cpp_root}/" DESTINATION "include/${PROJECT_NAME}")
  install(DIRECTORY "${_flux_py_root}/"
    DESTINATION "lib/python${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}/site-packages")
  ament_export_include_directories("include/${PROJECT_NAME}")
endmacro()
